In [2]:
# Import required libraries
# pandas → data manipulation
# numpy → numerical operations

import pandas as pd
import numpy as np

# Display full columns
pd.set_option('display.max_columns', None)

### <div class="alert alert-block alert-info"><b>Load dataset<b><div>

In [3]:
# Load dataset
# Load match-level dataset
matches=pd.read_csv( r"C:\Users\Akash\Downloads\IPL-Data-Analysis-Project\Datasets\matches.csv",low_memory=False)
# Load ball-by-ball dataset
deliveries=pd.read_csv( r"C:\Users\Akash\Downloads\IPL-Data-Analysis-Project\Datasets\deliveries.csv",low_memory=False)

### <div class="alert alert-block alert-info"><b>Data Validation <b><div>

In [4]:
matches.info()
print(30*"===")
matches.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   match_id         1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   object
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: float64(3), int64(1), object(16)
memory usage: 171.2+ KB
==========================================================================================

match_id              0
season                0
city                 51
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

In [5]:
deliveries.info()
print(30*"==")
deliveries.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  object
 3   bowling_team      260920 non-null  object
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  object
 7   bowler            260920 non-null  object
 8   non_striker       260920 non-null  object
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       14125 non-null   object
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  12950 non-null   object
 15  dismissal_kind    12950 non-null   object
 16  fielder           9354 non-null    object
dtypes: int64(8), object(9)
memory usage: 33.8+ MB
============================================================

match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
ball                     0
batter                   0
bowler                   0
non_striker              0
batsman_runs             0
extra_runs               0
total_runs               0
extras_type         246795
is_wicket                0
player_dismissed    247970
dismissal_kind      247970
fielder             251566
dtype: int64

### <div class="alert alert-block alert-info"><b>Remove Duplicate Rows<b><div>

In [6]:
# Remove duplicate rows from datasets
matches.drop_duplicates(inplace=True)
deliveries.drop_duplicates(inplace=True)

print("Duplicates removed successfully")

Duplicates removed successfully

### <div class="alert alert-block alert-info"><b>Handle Missing Values (matches)<b><div>

In [7]:
# Fill missing city values using venue

matches["city"] = matches["city"].fillna("Unknown")

In [8]:
# Fill missing winner value

matches["winner"]=matches["winner"].fillna("No Result")

In [9]:
matches["player_of_match"]=matches["player_of_match"].fillna("Not Awarded")

In [10]:
# Handle result_margin
# NULL → 0
matches["result_margin"] = matches["result_margin"].fillna(0)

In [11]:
matches["target_runs"]=matches["target_runs"].fillna(0)

matches["target_overs"]=matches["target_overs"].fillna(0)

In [12]:
# Handle method column
# NULL → Normal match
matches["method"] = matches["method"].fillna("Normal")

### <div class="alert alert-block alert-info"><b>City Name Standardization <b><div>

In [13]:
#city name Standardize
matches["city"]=matches["city"].replace({ "Bangalore" :"Bengaluru"})
# verify
matches[matches["city"]=="Bengalore" ]

Empty DataFrame
Columns: [match_id, season, city, date, match_type, player_of_match, venue, team1, team2, toss_winner, toss_decision, winner, result, result_margin, target_runs, target_overs, super_over, method, umpire1, umpire2]
Index: []

### <div class="alert alert-block alert-info"><b>Team Name Standardization Both dataset<b><div>

In [14]:
# Standardize Team Names
Team_standardization= {"Delhi Daredevils":"Delhi Capitals",
                      "Kings XI Punjab":"Punjab Kings" ,
                      "Rising Pune Supergiant" :"Rising Pune Supergiants" ,
                      "Royal Challengers Bangalore":"Royal Challengers Bengaluru" }

In [15]:
#Team - matches dataset

Team_columns=["team1","team2","toss_winner","winner"]
matches[Team_columns]=matches[Team_columns].replace(Team_standardization)
# verify
matches[Team_columns]

,team1,team2,toss_winner,winner
0,Royal Challengers Bengaluru,Kolkata Knight Riders,Royal Challengers Bengaluru,Kolkata Knight Riders
1,Punjab Kings,Chennai Super Kings,Chennai Super Kings,Chennai Super Kings
2,Delhi Capitals,Rajasthan Royals,Rajasthan Royals,Delhi Capitals
3,Mumbai Indians,Royal Challengers Bengaluru,Mumbai Indians,Royal Challengers Bengaluru
4,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,Kolkata Knight Riders
...,...,...,...,...
1090,Punjab Kings,Sunrisers Hyderabad,Punjab Kings,Sunrisers Hyderabad
1091,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,Kolkata Knight Riders
1092,Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,Rajasthan Royals
1093,Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,Sunrisers Hyderabad
1094,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,Kolkata Knight Riders

In [16]:
# Name standardization (batting_team , bowling_team) in deliveries dataset 

bat_bowl_column=["batting_team","bowling_team"]
deliveries[bat_bowl_column]=deliveries[bat_bowl_column].replace(Team_standardization)

#verify
deliveries[bat_bowl_column]

                 batting_team                 bowling_team
0       Kolkata Knight Riders  Royal Challengers Bengaluru
1       Kolkata Knight Riders  Royal Challengers Bengaluru
2       Kolkata Knight Riders  Royal Challengers Bengaluru
3       Kolkata Knight Riders  Royal Challengers Bengaluru
4       Kolkata Knight Riders  Royal Challengers Bengaluru
...                       ...                          ...
260915  Kolkata Knight Riders          Sunrisers Hyderabad
260916  Kolkata Knight Riders          Sunrisers Hyderabad
260917  Kolkata Knight Riders          Sunrisers Hyderabad
260918  Kolkata Knight Riders          Sunrisers Hyderabad
260919  Kolkata Knight Riders          Sunrisers Hyderabad

[260920 rows x 2 columns]

### <div class="alert alert-block alert-info"><b>Venue Standardization<b><div>

In [17]:
print((matches["venue"].nunique()))

venue_standardization = {

    "Arun Jaitley Stadium": "Arun Jaitley Stadium, Delhi",

    "Brabourne Stadium": "Brabourne Stadium, Mumbai",

    "Dr DY Patil Sports Academy": "Dr DY Patil Sports Academy, Mumbai",

    "Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium": "Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam",

    "Eden Gardens": "Eden Gardens, Kolkata",

    "Himachal Pradesh Cricket Association Stadium": "Himachal Pradesh Cricket Association Stadium, Dharamsala",

    # MA Chidambaram Stadium variants
    "MA Chidambaram Stadium": "MA Chidambaram Stadium, Chepauk, Chennai",
    "MA Chidambaram Stadium, Chepauk":"MA Chidambaram Stadium, Chepauk, Chennai",

    "Maharashtra Cricket Association Stadium":"Maharashtra Cricket Association Stadium, Pune",

    # Chinnaswamy variants
    "M Chinnaswamy Stadium":"M. Chinnaswamy Stadium, Bengaluru",
    "M.Chinnaswamy Stadium":"M. Chinnaswamy Stadium, Bengaluru",
    "M Chinnaswamy Stadium, Bengaluru":"M. Chinnaswamy Stadium, Bengaluru",

    # Mohali variants
    "Punjab Cricket Association Stadium, Mohali": "I.S. Bindra Punjab Cricket Association Stadium, Mohali",
    "Punjab Cricket Association IS Bindra Stadium":"I.S. Bindra Punjab Cricket Association Stadium, Mohali",
    "Punjab Cricket Association IS Bindra Stadium, Mohali":"I.S. Bindra Punjab Cricket Association Stadium, Mohali",
    "Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh":"I.S. Bindra Punjab Cricket Association Stadium, Mohali",

    # Hyderabad variants
    "Rajiv Gandhi International Stadium":"Rajiv Gandhi International Stadium, Uppal, Hyderabad",
    "Rajiv Gandhi International Stadium, Uppal":"Rajiv Gandhi International Stadium, Uppal, Hyderabad",
    "Rajiv Gandhi International Stadium Hyderabad":"Rajiv Gandhi International Stadium, Uppal, Hyderabad",
    
    # Jaipur
    "Sawai Mansingh Stadium":"Sawai Mansingh Stadium, Jaipur",
    "Sawai Mansingh Stadium Jaipur":"Sawai Mansingh Stadium, Jaipur",

    # Mumbai
    "Wankhede Stadium":"Wankhede Stadium, Mumbai",
    "Wankhede Stadium Mumbai":"Wankhede Stadium, Mumbai"
}


matches["venue"]=matches["venue"].replace(venue_standardization)
#verify
print(sorted(matches["venue"].unique()))
print(matches["venue"].nunique())

58
['Arun Jaitley Stadium, Delhi', 'Barabati Stadium', 'Barsapara Cricket Stadium, Guwahati', 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow', 'Brabourne Stadium, Mumbai', 'Buffalo Park', 'De Beers Diamond Oval', 'Dr DY Patil Sports Academy, Mumbai', 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam', 'Dubai International Cricket Stadium', 'Eden Gardens, Kolkata', 'Feroz Shah Kotla', 'Green Park', 'Himachal Pradesh Cricket Association Stadium, Dharamsala', 'Holkar Cricket Stadium', 'I.S. Bindra Punjab Cricket Association Stadium, Mohali', 'JSCA International Stadium Complex', 'Kingsmead', 'M. Chinnaswamy Stadium, Bengaluru', 'MA Chidambaram Stadium, Chepauk, Chennai', 'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur', 'Maharashtra Cricket Association Stadium, Pune', 'Narendra Modi Stadium, Ahmedabad', 'Nehru Stadium', 'New Wanderers Stadium', 'Newlands', 'OUTsurance Oval', 'Rajiv Gandhi International Stadium, Uppal, Hyderabad', 'Sardar Patel Stadium, Motera', 'Saurashtra Cricket Association Stadium', 'Sawai Mansingh Stadium, Jaipur', 'Shaheed Veer Narayan Singh International Stadium', 'Sharjah Cricket Stadium', 'Sheikh Zayed Stadium', "St George's Park", 'Subrata Roy Sahara Stadium', 'SuperSport Park', 'Vidarbha Cricket Association Stadium, Jamtha', 'Wankhede Stadium, Mumbai', 'Zayed Cricket Stadium, Abu Dhabi']
40

### <div class="alert alert-block alert-info"><b>Convert datatype <b><div>

In [18]:
# To Ensure Numeric Columns Proper
numeric_cols = [
    
    "batsman_runs",
    "extra_runs",
    "total_runs",
    "is_wicket"
]

deliveries[numeric_cols] = deliveries[numeric_cols].apply(pd.to_numeric)

In [19]:
# Convert date column to datetime format
# Dataset date format → DD-MM-YYYY
matches["date"] = pd.to_datetime(matches["date"],format="%d-%m-%Y")
print(matches["date"])

0      2008-04-18
1      2008-04-19
2      2008-04-19
3      2008-04-20
4      2008-04-20
          ...
1090   2024-05-19
1091   2024-05-21
1092   2024-05-22
1093   2024-05-24
1094   2024-05-26
Name: date, Length: 1095, dtype: datetime64[ns]

### <div class="alert alert-block alert-info"><b>Create Column<b><div>

In [20]:
#year column create
matches["year"]=matches["date"].dt.year

In [21]:
# Create match_phase column
def match_phase(over):
    
    if over <= 6:
        return "Powerplay"
    
    elif over <= 15:
        return "Middle Overs"
    
    else:
        return "Death Overs"

deliveries["match_phase"] = deliveries[
    "over"
].apply(match_phase)

In [22]:
# Create super_over flag
 #HANDLE INNING VALUES

deliveries["is_super_over"] = deliveries["inning"].apply(
    lambda x: 1 if x > 2 else 0
)

### <div class="alert alert-block alert-info"><b>Handle Missing Values (deliveries)<b><div>

In [23]:
# Fill missing extras_type
#  NULL → No Extra
deliveries["extras_type"] = deliveries["extras_type"].fillna("No Extra")

In [24]:
# player dismissed - NULL → Not Out
deliveries["player_dismissed"]=deliveries["player_dismissed"].fillna("Not Out")

# fielder NULL → Not out
deliveries["dismissal_kind"]=deliveries["dismissal_kind"].fillna("Not Out")

# fielder NULL
deliveries["fielder"]=deliveries["fielder"].fillna("None")

In [25]:
# Remove invalid overs if present more than 20 .
deliveries = deliveries[deliveries["over"] <= 20]

In [26]:
deliveries = deliveries[deliveries["ball"] <= 6]

### <div class="alert alert-block alert-info"><b>Final Data Validation<b><div>

In [27]:
matches.isnull().sum()

match_id           0
season             0
city               0
date               0
match_type         0
player_of_match    0
venue              0
team1              0
team2              0
toss_winner        0
toss_decision      0
winner             0
result             0
result_margin      0
target_runs        0
target_overs       0
super_over         0
method             0
umpire1            0
umpire2            0
year               0
dtype: int64

In [28]:
deliveries.isnull().sum()

match_id            0
inning              0
batting_team        0
bowling_team        0
over                0
ball                0
batter              0
bowler              0
non_striker         0
batsman_runs        0
extra_runs          0
total_runs          0
extras_type         0
is_wicket           0
player_dismissed    0
dismissal_kind      0
fielder             0
match_phase         0
is_super_over       0
dtype: int64

### <div class="alert alert-block alert-info"><b>Merge Datasets<b><div>

In [29]:
# ipl_data = pd.merge(deliveries , matches , on="match_id" , how="left" )

In [30]:
# ipl_data.info()

In [31]:
# ipl_data.isnull().sum()

### <div class="alert alert-block alert-info"><b>Save Cleaned Dataset<b><div>

In [32]:
# #matches.to_csv( "matches_cleaned.csv", index=False)

# deliveries.to_csv( "deliveries_cleaned.csv", index=False )
# ipl_data.to_csv( "ipl_dataset_cleaned.csv", index=False )

In [33]:

# # Save cleaned datasets for analysis and reuse
# matches.to_csv(r"C:\Users\Akash\Downloads\Dataset\matches_cleaned.csv",index=False)
# deliveries.to_csv(r"C:\Users\Akash\Downloads\Dataset\deliveries_cleaned.csv",index=False)
# ipl_data.to_csv( r"C:\Users\Akash\Downloads\Dataset\ipl_dataset_cleaned.csv", index=False)